let constant = {
  TRUE: true,
  FALSE: false,
  SUCCESSCODE: 200,
  ERRORCODE: 400,
  GEOFENCEERROR : "Please add the outlet in your geofence.",
  TRUEMSG: "Successful",
  FALSEMSG: "Something went wrong please try again later.",
  TOKENMISSING: "Authorization missing",
  TOKENNOTCORRECT: "Authorization not correct",
  PARAMETERMISSING: "Parameters missing.",
  NOACCOUNTMSG: "No account associated with this phone number",
  WRONGOLDPASSWORD: "Old password is not correct",
  OTPSEND: "Otp sent successfully",
  SENTMSG: "Sent successfully",
  ADDMSG: "Added successfully",
  OPTREQ: "Otp required",
  PHONEREQU: "Phone number required",
  INVALIDOTP: "Invalid Otp",
  UPDATEMSG: "Updated successfully",
  COUNTRYCODEREQ: "Country code required",
  INVALIDLINK: "Invalid link",
  DELETEMSG: "Deleted successfully",
  PASSCHANGEMSG: "Password changed successfully",
  INVALIDPARAMS: "Please check your credentials and try again!",
  NOTREGISTEREDEMAIL: "This email not registered with any account",
  NOTREGISTEREDPHONE: "This phone number not registered with any account",
  SOCIALREGISTERMSG: "Account created with social account you can not reset password",
  PHONEEXISTS: "This number is associated with another account",
  EMAILEXISTS: "This email is associated with another account",
  VEHICLENUMBEREXISTS: "Vehicle Number already registered",
  FOODCATEXISTS: "Food category already exists with this name.",
  FOODITEMEXISTS: "Food item already exists with this name.",
  RESTAURANTEXISTS: "Restaurant already exists with this name.",
  CANNOTCANCEL: "You can not cancel this order",
  STORECATEXISTS: "Category already exists with this name.",
  STORETYPEEXITS: "Store Type already exists with this name",
  ALREADYEXISTS: "Records already exists with this name.",
  STOREITEMEXISTS: "Item already exists with this name.",
  STOREEXISTS: "Store already exists with this name.",
  NEWPASSSAME: "New password can not same as old password.",
  OLDPASSMSG: "Old password not correct.",
  PROMOEXISTS: "Promocode already created with this code",
  CODENOTEXISTSNOW: "Promocode not applicable now",
  INVALIDCODE: "Applied promocode is not correct",
  RATEDMSG: "Rated successfully",
  MARKFAVMSG: "Marked favourite successfully",
  UNMARKFAVMSG: "Removed from favourite successfully",
  ORDERPLACED: "Order placed successfully",
  NOTDELIVERHERE: "Restaurant do not deliver here",
  ERRMSG: "Something went wrong please try again later.",
  LATEMSG: "Oops You are late, You can not accept this request",
  FILEMSG: "Image not provided",
  BASEURL: "http://13.232.208.65:9000",
  // Category Mesage
  INVALID_CATEGORY_ID: "Invalid Category Id",
  CATEGORY_DELETED_SUCCESSFULLY: "Category deleted successfully",
  FETCHED_SUCCESSFULLY: "Fetched successfully",
  //Taxi
  NODRIVER: "No driver found near to you. Please try later",
  USERONBOOKING: "User On have picked another ride",
  BOOKINGMSG: "Booking created successfully",
  REQUESTCANCEL: "User not looking for ride anymore ",
  //Images Url
  USERIMAGE: "/static/users/",
  FOODCATIMAGE: "/static/foodCategory/",
  RESTAURANTIMAGE: "/static/restaurants/",
  FOODITEMIMAGE: "/static/foodItems/",
  DRIVERIMAGE: "/static/drivers/",
  VEHICLETYPEIMAGE: "/static/vehicleTypes/",
  DRIVERDOCUMENTSIMAGE: "/static/driverDocuments/",
  PATHIMAGES: "/static/pathImages/",
  STORECATIMAGE: "/static/storeCategory/",
  STOREIMAGE: "/static/stores/",
  STOREITEMIMAGE: "/static/storeItems/",
  CATSUBCATIMAGE: "/static/categorySubCategories/",
  BRANDIMAGE: "/static/brands/",
  CSVIMAGE: "/static/csv/",
  BANNERIMAGE: "/static/banner/",
  ADMINIMAGE: "/static/admin/",
  PROMOCODEIMAGE: "/static/promoCode/",
  TOPPINGIMAGE: "/static/topping/",
  APPSETTINGIMAGE: "/static/appImages/",
  RADIUSCIRCLE: 500000,
  DRIVERRADIUS: 300000,
  LIMIT: 12,
  ADMINLIMIT: 10,
  // DRIVER:
  VEHICLETYPEEXISTS: "Vehicle category already added",
  // DRIVER:
  VEHICLETYPEEXISTS: "Vehicle category already added",
  //stuttle
  ALREADYEXIST: " already exists.",
  DRIVERUNAVAILABLE: "Driver already engaged.",
  NORIDE: "No ride is allocated to this driver",
  NOTFOUNDRECORD: "No record found of ",
  ROUTENOTFOUND: "Route not correct. Please check again",
  SEATBOOKED: "Seat number already booked",
  CANCELMSG: "Seat booking canceled successfully",
  NUMBER_OF_RETRY: 1,
  BANNER_TYPE: {
    OFFER: 1,
    ADVERTISEMENT: 2,
  },
  ROLE: {
    SUPER_ADMIN: 1,
    ADMIN: 2,
  },
  VERTICALTYPE: {
    RESTAURANT: 0,
    STORE: 1,
    TAXI: 2,
    SHUTTLE: 3,
  },
  SUB_VERTICAL_TYPE: {
    RESTAURANT: 0,
    STORE: 1,
  },
  DRIVERTYPE: {
    SALARIED: 0,
    COMMISSION: 1,
    BOTH_SALARIED_COMMISSION: 2,
  },
  FOODTYPE: {
    VEG: 0,
    NON_VEG: 1,
    BOTH: 2,
  },
  USER_STATUS: {
    BLOCK: 0,
    UNBLOCK: 1,
    DELETED: 2,
  },
  USER_TYPE: {
    USER: 0,
    DRIVER: 1,
    STORE: 2,
    RESTAURANT: 3,
    MERCHANT : 4
  },
  ORDERSTATUS: {
    PENDING: 0,
    ACCEPT: 1,
    REACHED_STORE: 2,
    PICKUP: 3,
    DELIVERD: 4,
    RATE: 5,
    SKIP: 6,
    CANCEL_BY_USER: 11,
    CANCEL_BY_RESTURANT: 12,
  },
  ORDER_FILTER_STATUS: {
    COMPLETED: 1,
    ONGOING: 2,
  },
  ROLE: {
    SUPER_ADMIN: 1,
    ADMIN: 2,
  },
  STORE_ORDERSTATUS: {
    PENDING: 0,
    ASSIGNED: 1,
    PROCESSED: 2,
    PICKEDUP: 3,
    DISPATCHED: 4,
    COMPLETED: 5,
    CANCELED: 6,
  },
  MODULES: [{
      displayName: "Dashboard",
      moduleCode: 2.0,
      isAdd: false,
      isEdit: false,
      isView: true,
      isDelete: false,
      isFilter: false,
      isSort: false,
      isSetStatus: false,
      isDeleted: false,
      isBlocked: false,
    },
    {
      displayName: "User",
      moduleCode: 4.0,
      isAdd: true,
      isEdit: true,
      isView: true,
      isDelete: true,
      isFilter: true,
      isSort: true,
      isSetStatus: true,
      isDeleted: false,
      isBlocked: false,
    },
    {
      displayName: "Driver",
      moduleCode: 8.0,
      isAdd: true,
      isEdit: true,
      isView: true,
      isDelete: true,
      isFilter: true,
      isSort: true,
      isSetStatus: true,
      isDeleted: false,
      isBlocked: false,
    },
    {
      displayName: "Restaurant",
      moduleCode: 16.0,
      isAdd: true,
      isEdit: true,
      isView: true,
      isDelete: true,
      isFilter: true,
      isSort: true,
      isSetStatus: true,
      isDeleted: false,
      isBlocked: false,
    },
    {
      displayName: "Store",
      moduleCode: 32.0,
      isAdd: true,
      isEdit: true,
      isView: true,
      isDelete: true,
      isFilter: true,
      isSort: true,
      isSetStatus: true,
      isDeleted: false,
      isBlocked: false,
    },
    {
      displayName: "Vehicle Type",
      moduleCode: 64.0,
      isAdd: true,
      isEdit: true,
      isView: true,
      isDelete: true,
      isFilter: false,
      isSort: true,
      isSetStatus: true,
      isDeleted: false,
      isBlocked: false,
    },
    {
      displayName: "Coupon",
      moduleCode: 128.0,
      isAdd: true,
      isEdit: true,
      isView: true,
      isDelete: true,
      isFilter: true,
      isSort: true,
      isSetStatus: true,
      isDeleted: false,
      isBlocked: false,
    },
    {
      displayName: "CMS Pages",
      moduleCode: 512.0,
      isAdd: true,
      isEdit: true,
      isView: true,
      isDelete: true,
      isFilter: true,
      isSort: true,
      isSetStatus: true,
      isDeleted: false,
      isBlocked: false,
    },
    {
      displayName: "Profile",
      moduleCode: 1024.0,
      isAdd: true,
      isEdit: true,
      isView: true,
      isDelete: true,
      isFilter: true,
      isSort: true,
      isSetStatus: true,
      isDeleted: false,
      isBlocked: false,
    },
    {
      displayName: "Change Password",
      moduleCode: 2048,
      isAdd: true,
      isEdit: true,
      isView: true,
      isDelete: true,
      isFilter: true,
      isSort: true,
      isSetStatus: true,
      isDeleted: false,
      isBlocked: false,
    },
    {
      displayName: "Admin Setting",
      moduleCode: 4096,
      isAdd: true,
      isEdit: true,
      isView: true,
      isDelete: true,
      isFilter: false,
      isSort: true,
      isSetStatus: true,
      isDeleted: false,
      isBlocked: false,
    },
  ],
  BOOKING_STATUS: {
    DEFAULT: 0,
    PENDING: 1,
    ACCEPTED: 2,
    COMPLETED: 3,
    ARRIVED: 4,
    STARTED: 6,
    ONGOING: 7,
    CANCELED: 8,
    OUT_FOR_DELIVERY: 9,
    PACKAGES_PICKED: 10,
    TRANSIT: 11,
    PARTIAL: 12,
    UPCOMING: 13,
    SCHEDULED: 15,
    ARRIVED_AT_PICKED: 16,
    PICKED: 17,
    ARRIVED_AT_DROPED: 19,
    DROPED: 20,
    START_RETURN: 21,
    END_RETURN: 22,
    AVAILABLE: 23,
    NOT_AVAILABLE: 24,
    NONE: 25,
    FUTURE: 26
  },
  BOOKING_TYPE: {
    RIDE: 1,
    DELIVERY: 2,
    DEFAULT: 0
  },
  PAYMENT_MODE: {
    CASH: 1,
    CARD: 2,
    WALLET: 3
  },
  PAYMENT_STATUS: {
    PENDING: 1,
    COMPLETED: 2,
    CANCEL: 3,
  },
  LOGIN_TYPE: {
    WITHOUTOTP: 0,
    WITHOTP: 1
  },
  IMAGE_TYPE : {
    BOTH : 1,
    FRONT : 2
  },
  VALIDATION_TYPE : {
    WEEK : 1,
    MONTH : 2,
    YEAR : 3
  }
};

export default constant;